apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dotnet-service
  title: Dotnet Service
  description: Dotnet service
  tags:
    - app
spec:
  type: service
  lifecycle: production
  owner: product
  system: dotnet
  dependsOn:
    - component:dotnet-library
  providesApis:
    - common-openapi
