apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gotham-deno-commons
  description: Gotham Deno commons library
  labels:
    frontseat.dev/language: typescript
spec:
  type: library
  lifecycle: production
  owner: wayne-enterprises
  dependencyOf:
    - component:default/backoffice-library
