apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mandates-service
  description: Mandates domain service
  labels:
    frontseat.dev/language: rust
spec:
  type: service
  lifecycle: production
  owner: birds-of-prey
  domain: retail-banking
  system: mandates-system
  dependsOn:
    - component:default/mandates-library
