apiVersion: jib/v1alpha1
kind: BuildFile
from:
  image: alpine:3.19
workingDirectory: /app
layers:
  entries:
    - name: binary
      files:
        - src: ${ARTIFACT}
          dest: /app/mandates-service
entrypoint:
  - ./mandates-service
exposedPorts:
  - "8080"
