apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: notification-service
  description: CoinHub Notification microservice
  annotations:
    frontseat.io/type: "maven"
  tags:
    - java
    - maven
    - spring-boot
    - microservice
    - coinhub
spec:
  type: service
  lifecycle: production
  owner: platform
  system: notification
  dependsOn:
    - component:core
  consumesApis:
    - account-events
    - transaction-events
