apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gotham-rust-commons
  description: Gotham Financial common Rust library
  labels:
    frontseat.dev/language: rust
spec:
  type: library
  lifecycle: production
  owner: wayne-enterprises
  dependencyOf:
    - component:default/mandates-library
