apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: common-maven-library
  description: Maven library
  tags:
    - maven
    - java
spec:
  type: library
  lifecycle: production
  owner: demo
  dependsOn:
    - component:default/common-maven-parent
  dependencyOf:
    - component:default/maven-library
