<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CoinHub.TransactionService</RootNamespace>
    <AssemblyName>dotnet-service</AssemblyName>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <PublishTrimmed>false</PublishTrimmed>
    <PublishDir>bin/</PublishDir>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../libs/dotnet-lib/CoinHub.Common.csproj" />
  </ItemGroup>

</Project>
