[project]
name = "recommendationservice"
version = "0.0.0"
requires-python = ">=3.12"
dependencies = [
    "google-api-core>=2.28.1",
    "grpcio-health-checking>=1.76.0",
    "python-json-logger>=4.0.0",
    "requests>=2.32.5",
    "rsa>=4.9.1",
    "opentelemetry-distro>=0.60b1",
    "opentelemetry-instrumentation-grpc>=0.60b1",
    "opentelemetry-exporter-otlp-proto-grpc>=1.39.1",
]

[tool.setuptools]
py-modules = ["recommendation_server", "client", "logger", "demo_pb2", "demo_pb2_grpc"]

[tool.ruff]
exclude = ["*_pb2.py", "*_pb2_grpc.py"]
