apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: deno-site
  title: Deno Site
  description: Deno site
  tags:
    - app
spec:
  type: site
  lifecycle: production
  owner: product
  system: deno
  dependsOn:
    - component:deno-library
  consumesApis:
    - common-openapi
