apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: deno-site
  description: Deno site
  labels:
    frontseat.dev/language: typescript
spec:
  type: service
  lifecycle: production
  owner: demo
  domain: frontseat-demo
