apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: online-boutique
  description: Online Boutique - a cloud-first microservices demo application
spec:
  owner: platform-team
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: boutique
  description: Online Boutique e-commerce platform
spec:
  owner: platform-team
  domain: online-boutique
