apiVersion: frontseat.io/v1alpha1
kind: Workspace
metadata:
  name: online-boutique
spec:
  plugins:
    frontseat/backstage: {}
    frontseat/docker: {}
    frontseat/dotnet: {}
    frontseat/gib: {}
    frontseat/go: {}
    frontseat/maven: {}
    frontseat/mise: {}
    frontseat/node: {}
    frontseat/npm: {}
    frontseat/protobuf: {}
    frontseat/ruff: {}
    frontseat/spectral: {}
    frontseat/uv: {}
  version: latest
