apiVersion: frontseat.io/v1alpha1
kind: Workspace
metadata:
  name: frontseat-demo
spec:
  version: latest
  plugins:
    frontseat/backstage: {}
    frontseat/deno: {}
    frontseat/docker: {}
    frontseat/dotnet: {}
    frontseat/github: {}
    frontseat/go: {}
    frontseat/helm: {}
    frontseat/jib: {}
    frontseat/maven: {}
    frontseat/mise: {}
    frontseat/npm: {}
    frontseat/release-conventional-commits: {}
    frontseat/release-flow: {}
    frontseat/rust: {}
    frontseat/vite: {}
