apiVersion: frontseat.io/v1alpha1
kind: Workspace
metadata:
  name: frontseat-demo
spec:
  ai:
    options:
      host: http://localhost:11434
    provider: ollama
  branching:
    strategy: release-flow
  platform:
    targets:
      - linux/amd64
      - darwin/arm64
      - windows/amd64
  plugins:
    frontseat/backstage: {}
    frontseat/docker: {}
    frontseat/dotnet: {}
    frontseat/github: {}
    frontseat/go: {}
    frontseat/maven: {}
    frontseat/mise: {}
    frontseat/node: {}
    frontseat/release-conventional-commits: {}
    frontseat/release-flow: {}
    frontseat/release-manual: {}
  ship:
    strategy: conventional-commits
  runner:
    type: reapi
    options:
      address: "localhost:50051"
      logstreamAddress: "localhost:50052"
  tools:
    manager:
      type: mise
