<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.google.onlineboutique</groupId>
    <artifactId>online-boutique</artifactId>
    <version>0.0.0</version>
    <packaging>pom</packaging>

    <name>Online Boutique</name>
    <description>Online Boutique - a cloud-first microservices demo application</description>

    <modules>
        <module>adservice</module>
    </modules>

    <distributionManagement>
        <repository>
            <id>github</id>
            <name>GitHub Packages</name>
            <url>https://maven.pkg.github.com/jbadeau/frontseat-demo</url>
        </repository>
    </distributionManagement>
</project>
