apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payments-library
  description: Gotham Financial payments library
  labels:
    frontseat.dev/language: java
spec:
  type: library
  lifecycle: production
  owner: bat-family
  domain: retail-banking
  system: payments-system
  dependsOn:
    - component:default/gotham-java-commons
    - component:default/payments-parent
  dependencyOf:
    - component:default/payments-service
