apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: transaction-events
  description: Event-driven API for transaction events
  annotations:
    frontseat.io/type: "asyncapi"
  tags:
    - events
    - kafka
    - transactions
    - coinhub
spec:
  type: asyncapi
  lifecycle: production
  owner: platform
  system: transaction
  definition: "unknown"
