apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: maven-library
  Title: Maven Library
  description: Maven library
  tags:
    - demo
spec:
  type: library
  lifecycle: production
  owner: demo
  system: maven