apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: common-openapi
  title: Common OpenAPI
  description: Common openapi
  tags:
    - common
spec:
  type: openapi
  lifecycle: production
  owner: system
  system: common-api
  definition:
    $text: ./openapi.yaml
