apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: partners-openapi
  description: Partners management API
  labels:
    frontseat.dev/language: openapi
spec:
  type: openapi
  lifecycle: production
  owner: justice-league
  domain: capital-markets
  system: partners-system
  definition: |
    $text: ./openapi.yaml
