apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gotham-vite-commons
  description: Gotham Financial common Vite library
  labels:
    frontseat.dev/language: typescript
spec:
  type: library
  lifecycle: production
  owner: wayne-enterprises
  domain: gotham-financial
  dependencyOf:
    - component:default/portal-library
