apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: loadgenerator
  description: Load testing with Locust
  annotations:
    frontseat.dev/plugins: "uv, docker"
  labels:
    frontseat.dev/language: python
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: boutique
  dependsOn:
    - component:default/frontend
