apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gotham-java-bom
  description: Gotham Financial Java BOM
  labels:
    frontseat.dev/language: java
spec:
  type: library
  lifecycle: production
  owner: wayne-enterprises
  dependsOn:
    - component:default/gotham-java-parent
