<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.gothamfinancial</groupId>
        <artifactId>gotham-java-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../gotham-java-parent/pom.xml</relativePath>
    </parent>

    <artifactId>gotham-java-bom</artifactId>
    <packaging>pom</packaging>
    <description>Gotham Financial Java BOM for dependency management</description>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.gothamfinancial</groupId>
                <artifactId>gotham-java-commons</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
