<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>accounts-library</AssemblyName>
    <RootNamespace>GothamFinancial.Accounts</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <Version>0.0.0</Version>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../platform/gotham-dotnet-platform/gotham-dotnet-commons/gotham-dotnet-commons.csproj" />
  </ItemGroup>

</Project>
