apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: adservice
  description: Serves contextual advertisements
  annotations:
    frontseat.dev/plugins: "maven, gib"
  labels:
    frontseat.dev/language: java
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: boutique
  providesApis:
    - api:default/boutique-proto
  dependencyOf:
    - component:default/frontend
