apiVersion: jib/v1alpha1
kind: BuildFile
from:
  image: eclipse-temurin:21-jre-alpine
entrypoint:
  - java
  - -Xms256m
  - -Xmx512m
  - -cp
  - /app/resources:/app/classes:/app/libs/*
  - hipstershop.AdService
exposedPorts:
  - "9555"
