apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dotnet-service
  description: CoinHub .NET microservice
  annotations:
    frontseat.io/type: "dotnet"
  tags:
    - dotnet
    - microservice
    - coinhub
spec:
  type: service
  lifecycle: production
  owner: platform
  system: coinhub
