apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: common-dotnet-library
  description: Common .NET library
  labels:
    frontseat.dev/language: csharp
spec:
  type: library
  lifecycle: production
  owner: demo
  domain: frontseat-demo
  dependencyOf:
    - component:default/dotnet-library
