apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: common-dotnet-library
  title: Common Dotnet Library
  description: Common Dotnet library
  tags:
    - common
spec:
  type: library
  lifecycle: production
  owner: system
  system: common-dotnet
