apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: payments-openapi
  description: Gotham Financial payments processing API
  labels:
    frontseat.dev/language: openapi
spec:
  type: openapi
  lifecycle: production
  owner: bat-family
  system: payments-system
  domain: retail-banking
  definition: |
    $text: ./openapi.yaml
