apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: go-library
  title: Go Library
  description: Go library
  tags:
    - demo
spec:
  type: library
  lifecycle: production
  owner: demo
  system: go
  dependsOn:
    - component:common-go-library
