apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rust-service
  description: Rust service
  tags:
    - rust
spec:
  type: service
  lifecycle: production
  owner: demo
  dependsOn:
    - component:default/rust-library
