apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: coinhub-ui
  description: CoinHub web user interface
  annotations:
    frontseat.io/type: "deno"
  tags:
    - deno
    - typescript
    - frontend
    - coinhub
spec:
  type: website
  lifecycle: production
  owner: platform
  system: coinhub
  consumesApis:
    - auth-api
    - account-api
    - transaction-api
