apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: common-maven-parent
  Title: Common Maven Parent
  description: Common maven parent
  tags:
    - common
spec:
  type: library
  lifecycle: production
  owner: system
  system: common-maven