apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: checkoutservice
  description: Handles checkout and orchestrates payment, shipping, and email
  annotations:
    frontseat.dev/plugins: "go, docker"
  labels:
    frontseat.dev/language: go
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: boutique
  ship:
    strategy: conventional-commits
  branching:
    strategy: release-flow
  consumesApis:
    - api:default/boutique-proto
  dependsOn:
    - api:default/boutique-proto
    - api:default/protos
    - component:default/cartservice
    - component:default/currencyservice
    - component:default/emailservice
    - component:default/paymentservice
    - component:default/productcatalogservice
    - component:default/shippingservice
  dependencyOf:
    - component:default/frontend
  projects:
    - checkoutservice
