apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: account
  description: Account management system
  tags:
    - accounts
    - banking
    - coinhub
spec:
  owner: platform
  domain: coinhub
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: account-system
  description: Account system components
spec:
  targets:
    - ./api/catalog-info.yaml
    - ./events/catalog-info.yaml
    - ./service/catalog-info.yaml
    - ./lib/catalog-info.yaml
