apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: deno-library
  title: Deno Library
  description: Deno library
  tags:
    - app
spec:
  type: library
  lifecycle: production
  owner: product
  system: deno
  dependsOn:
    - component:common-deno-library
