apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: deno-library
  description: Deno library
  labels:
    frontseat.dev/language: typescript
spec:
  type: library
  lifecycle: production
  owner: demo
  domain: frontseat-demo
