apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: maven-parent
  Title: Maven Parent
  description: Maven parent
  tags:
    - demo
spec:
  type: library
  lifecycle: production
  owner: demo
  system: maven