apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: common-deno-library
  description: Common Deno library
  tags:
    - deno
    - typescript
spec:
  type: library
  lifecycle: production
  owner: demo
