apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: common-deno-library
  title: Common Deno Library
  description: Common Deno library
  tags:
    - common
spec:
  type: library
  lifecycle: production
  owner: system
  system: common-deno
