apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: account-events
  description: Event-driven API for account lifecycle events
  annotations:
    frontseat.io/type: "asyncapi"
  tags:
    - events
    - kafka
    - accounts
    - coinhub
spec:
  type: asyncapi
  lifecycle: production
  owner: platform
  system: account
  definition: "unknown"