apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: portal-site
  description: Portal site for Gotham Financial
  labels:
    frontseat.dev/language: typescript
spec:
  type: service
  lifecycle: production
  owner: green-lantern-corps
  system: portal-system
  domain: retail-banking
  dependsOn:
    - component:default/portal-library
