apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backoffice-site
  description: Backoffice compliance dashboard
  labels:
    frontseat.dev/language: typescript
spec:
  type: service
  lifecycle: production
  owner: suicide-squad
  domain: capital-markets
  system: backoffice-system
  dependsOn:
    - component:default/backoffice-library
