apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: transaction-service
  description: CoinHub Transaction microservice
  annotations:
    frontseat.io/type: "rust"
  tags:
    - rust
    - microservice
    - coinhub
spec:
  type: service
  lifecycle: production
  owner: platform
  system: transaction
  dependsOn:
    - component:transaction-lib
  providesApis:
    - transaction-api
    - transaction-events
