apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: accounts-openapi
  description: Accounts OpenAPI specification
  labels:
    frontseat.dev/language: openapi
spec:
  type: openapi
  lifecycle: production
  owner: teen-titans
  domain: retail-banking
  system: accounts-system
  definition: |
    $text: ./openapi.yaml
