apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dotnet-library
  description: .NET library
  labels:
    frontseat.dev/language: csharp
spec:
  type: library
  lifecycle: production
  owner: demo
  domain: frontseat-demo
  dependsOn:
    - component:default/common-dotnet-library
  dependencyOf:
    - component:default/dotnet-service
