apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gotham-dotnet-commons
  description: Gotham Financial .NET platform commons library
  labels:
    frontseat.dev/language: csharp
spec:
  type: library
  lifecycle: production
  owner: wayne-enterprises
  domain: retail-banking
  dependencyOf:
    - component:default/accounts-library
