apiVersion: jib/v1alpha1
kind: BuildFile

from:
  image: gcr.io/distroless/base-debian12

entrypoint:
  - /app/transaction-service

labels:
  org.opencontainers.image.title: transaction-service
  org.opencontainers.image.description: CoinHub Transaction Service

layers:
  entries:
    - name: app
      files:
        - src: bin/transaction-service
          dest: /app/transaction-service
      properties:
        filePermissions: "755"
