apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: common-asyncapi
  title: Common AsyncAPI
  description: Common asyncapi
  tags:
    - common
spec:
  type: asyncapi
  lifecycle: production
  owner: system
  system: common-api
  definition:
    $text: ./asyncapi.yaml
