apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payments-service
  description: Gotham Financial payments service
  labels:
    frontseat.dev/language: java
spec:
  type: service
  lifecycle: production
  owner: bat-family
  domain: retail-banking
  system: payments-system
  dependsOn:
    - component:default/payments-library
    - component:default/payments-parent
