apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: maven-service
  description: Maven library
  tags:
    - maven
    - java
spec:
  type: service
  lifecycle: production
  owner: demo
  dependsOn:
    - component:default/maven-library
    - component:default/maven-parent
