apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: maven-service
  title: Maven Service
  description: Maven service
  tags:
    - app
spec:
  type: service
  lifecycle: production
  owner: product
  system: maven
  providesApis:
    - common-openapi
