apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: maven-service
  title: Maven Service
  description: Maven service
  tags:
    - demo
spec:
  type: service
  lifecycle: production
  owner: demo
  system: maven
