apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: transaction
  description: Transaction processing system
  tags:
    - transactions
    - banking
    - coinhub
spec:
  owner: platform
  domain: coinhub
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: transaction-system
  description: Transaction system components
spec:
  targets:
    - ./api/catalog-info.yaml
    - ./events/catalog-info.yaml
    - ./service/catalog-info.yaml
    - ./lib/catalog-info.yaml
