apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payments-parent
  description: Gotham Financial payments parent POM
  labels:
    frontseat.dev/language: java
spec:
  type: library
  lifecycle: production
  owner: bat-family
  domain: retail-banking
  system: payments-system
  dependencyOf:
    - component:default/payments-library
    - component:default/payments-service
