apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: go-service
  description: CoinHub Go microservice
  annotations:
    frontseat.io/type: "go"
  tags:
    - go
    - microservice
    - coinhub
spec:
  type: service
  lifecycle: production
  owner: platform
  system: coinhub
