apiVersion: jib/v1alpha1
kind: BuildFile

from:
  image: gcr.io/distroless/base-debian12

entrypoint:
  - /app/go-service

labels:
  org.opencontainers.image.title: go-service
  org.opencontainers.image.description: CoinHub Go Service

layers:
  entries:
    - name: app
      files:
        - src: bin/go-service
          dest: /app/go-service
      properties:
        filePermissions: "755"
