apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: portal-library
  description: Portal library for Gotham Financial
  labels:
    frontseat.dev/language: typescript
spec:
  type: library
  lifecycle: production
  owner: green-lantern-corps
  system: portal-system
  domain: retail-banking
  dependsOn:
    - component:default/gotham-vite-commons
  dependencyOf:
    - component:default/portal-site
