apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: portal
  description: CoinHub portal system
  tags:
    - frontend
    - web
    - coinhub
spec:
  owner: platform
  domain: coinhub
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: portal-system
  description: Portal system components
spec:
  targets:
    - ./web/catalog-info.yaml
