apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: common-maven-bom
  Title: Common Maven BOM
  description: Common maven bom
  tags:
    - demo
spec:
  type: library
  lifecycle: production
  owner: demo
  system: common-maven
