apiVersion: jib/v1alpha1
kind: BuildFile

from:
  image: gcr.io/distroless/base-debian12

entrypoint:
  - /app/auth-service

labels:
  org.opencontainers.image.title: auth-service
  org.opencontainers.image.description: CoinHub Authentication Service

layers:
  entries:
    - name: app
      files:
        - src: bin/auth-service
          dest: /app/auth-service
      properties:
        filePermissions: "755"
